services:
  frontend:
    build: ../minix_frontend
    container_name: minix_frontend
    depends_on:
      backend:
        condition: service_started
    ports:
      - "3000:80"
  backend:
    build: ../minix_backend
    container_name: minix_backend
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@database:5432/${DB_NAME}?schema=public"
      JWT_ACCESS_SECRET: "JWT_ACCESS_SECRET"
      JWT_REFRESH_SECRET: "JWT_REFRESH_SECRET"
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: [ "sh", "-c", "npx prisma migrate deploy && node dist/index.js" ]
  database:
    image: postgres:17.0
    container_name: minix_postgresql
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: { }